# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate `docs/commands.md` from the slash-command registry.

Usage:
    uv run python scripts/generate_commands_catalog.py           # writes docs/commands.md
    uv run python scripts/generate_commands_catalog.py --check   # exits 1 if stale

Runs offline: imports only the registry (`horizon.commands`), which needs
neither GCP creds nor the optional extras.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

sys.path.insert(0, str(_REPO_ROOT))

from horizon.commands import BUILTIN_COMMAND_REGISTRY  # noqa: E402

_OUTPUT = _REPO_ROOT / "docs" / "commands.md"

_BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate_commands_catalog.py — do not edit "
    "manually. Regenerate with `make commands-catalog`. -->"
)

_INTRO = (
    "Reference for Long Horizon's built-in slash commands — the user-facing affordances "
    "(swap models, force a memory rollup, grant a HITL bypass, refresh skills, …) "
    "that `make_slash_command_dispatcher` intercepts before the model runs. Names "
    "come from `horizon/commands/__init__.py`; regenerate after changing the "
    "registry."
)

# Behaviour-derived fallbacks for handlers without a docstring first line. The
# registry stores callables, not descriptions, so the curated text lives here.
_FALLBACK_DESCRIPTIONS: dict[str, str] = {
    "dream-review": (
        "Force an immediate dream-review pass, consolidating your Structured "
        "Profile from recent sessions."
    ),
    "grant": (
        "Grant a per-session HITL bypass for a terminal command (no args lists "
        "active grants)."
    ),
    "model": (
        "Show or switch the root agent model for this session (no args lists "
        "available models)."
    ),
    "permissions": (
        "List session and persisted permission grants; `clear` drops the session "
        "grants."
    ),
    "reload": (
        "Reload the skill catalog and invalidate cached secrets for this session."
    ),
    "routines": "List your scheduled routines; `remove <id>` cancels one.",
    "sandbox-upgrade": (
        "Upgrade your sandbox to the current runtime image and migrate the workspace."
    ),
    "workspace": "Show, set, or clear the per-session workspace focus directory.",
    "yolo": (
        "Toggle YOLO approval mode (auto-approve risky commands; exfil and "
        "catastrophic blocks remain)."
    ),
}


def _describe(name: str, handler: object) -> str:
    doc = (getattr(handler, "__doc__", None) or "").strip()
    if doc:
        return doc.splitlines()[0].strip()
    fallback = _FALLBACK_DESCRIPTIONS.get(name)
    if fallback:
        return fallback
    # Never emit a blank cell: a new command without a docstring or fallback
    # surfaces a visible placeholder that fails review rather than silently.
    return f"(no description — add a docstring or fallback for `/{name}`)"


def _fmt_cell(text: str) -> str:
    return text.replace("|", "\\|") if text else ""


def generate() -> str:
    """Return the full markdown content for `docs/commands.md`."""
    commands = sorted(BUILTIN_COMMAND_REGISTRY.items(), key=lambda kv: kv[0])

    lines: list[str] = [
        _BANNER,
        "# Slash command catalog",
        "",
        _INTRO,
        "",
        "_Auto-generated from `horizon/commands/__init__.py`. "
        "Regenerate with `make commands-catalog`._",
        "",
        f"## Commands ({len(commands)})",
        "",
        "| Command | Description |",
        "| --- | --- |",
    ]
    for name, handler in commands:
        lines.append(
            f"| {_fmt_cell(f'`/{name}`')} | {_fmt_cell(_describe(name, handler))} |"
        )
    lines.extend(
        [
            "",
            "## Where to go next",
            "",
            "- [docs/configuration.md](configuration.md) — environment variables and "
            "dependency extras.",
            "- [../AGENTS.md](../AGENTS.md) — architecture, subsystems, and "
            "contribution rules.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that docs/commands.md is up-to-date (exit 1 if stale).",
    )
    args = parser.parse_args()

    expected = generate()

    if args.check:
        if not _OUTPUT.exists():
            print(f"MISSING: {_OUTPUT}", file=sys.stderr)
            print("Run `make commands-catalog` to regenerate.", file=sys.stderr)
            raise SystemExit(1)
        actual = _OUTPUT.read_text(encoding="utf-8")
        if actual != expected:
            diff = difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile="docs/commands.md (on disk)",
                tofile="docs/commands.md (expected)",
                lineterm="",
            )
            print(f"STALE: {_OUTPUT}\n", file=sys.stderr)
            print("\n".join(diff), file=sys.stderr)
            print(
                "\nRun `make commands-catalog` to regenerate.", file=sys.stderr
            )
            raise SystemExit(1)
        print(f"OK: {_OUTPUT} is up-to-date")
    else:
        _OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
